// Code generated by mockery. DO NOT EDIT.

package dao

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockSqlxDB is an autogenerated mock type for the sqlxDB type
type mockSqlxDB struct {
	mock.Mock
}

// SelectContext provides a mock function with given fields: ctx, dest, query, args
func (_m *mockSqlxDB) SelectContext(ctx context.Context, dest interface{}, query string, args ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, ctx, dest, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, string, ...interface{}) error); ok {
		r0 = rf(ctx, dest, query, args...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
