// Code generated by mockery. DO NOT EDIT.

package service

import (
	context "context"

	dao "github.com/ryan-holcombe/testable-golang/dao"
	mock "github.com/stretchr/testify/mock"
)

// mockUserDAO is an autogenerated mock type for the userDAO type
type mockUserDAO struct {
	mock.Mock
}

// FindAll provides a mock function with given fields: ctx
func (_m *mockUserDAO) FindAll(ctx context.Context) ([]dao.UserModel, error) {
	ret := _m.Called(ctx)

	var r0 []dao.UserModel
	if rf, ok := ret.Get(0).(func(context.Context) []dao.UserModel); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dao.UserModel)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
