// Code generated by mockery. DO NOT EDIT.

package api

import (
	context "context"

	service "github.com/ryan-holcombe/testable-golang/service"
	mock "github.com/stretchr/testify/mock"
)

// mockUserTicketsService is an autogenerated mock type for the userTicketsService type
type mockUserTicketsService struct {
	mock.Mock
}

// FindAll provides a mock function with given fields: ctx
func (_m *mockUserTicketsService) FindAll(ctx context.Context) ([]service.UserWithTickets, error) {
	ret := _m.Called(ctx)

	var r0 []service.UserWithTickets
	if rf, ok := ret.Get(0).(func(context.Context) []service.UserWithTickets); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.UserWithTickets)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
