// Code generated by mockery. DO NOT EDIT.

package api

import (
	service "github.com/ryan-holcombe/testable-golang/service"
	mock "github.com/stretchr/testify/mock"
)

// mockUserTicketsService is an autogenerated mock type for the userTicketsService type
type mockUserTicketsService struct {
	mock.Mock
}

// FindAll provides a mock function with given fields:
func (_m *mockUserTicketsService) FindAll() ([]service.UserWithTickets, error) {
	ret := _m.Called()

	var r0 []service.UserWithTickets
	if rf, ok := ret.Get(0).(func() []service.UserWithTickets); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.UserWithTickets)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
